### ISSUE TITLE
Implementation Questions

### ISSUE THREAD

**Issue by abieler** [scivision/python-performance#2]
I noticed a few differences in implementation of the simple iteration algoritm that I do not understand:
(only speaking about the scripts in the pisum section)

1) Fortran version only times the loop,  not memory allocation of all variables etc.
    Fortran version runs multiple times and reports the fastest run

2) Julia uses Floats for the variable ii. Using an Int instead results in a x15 speed up.
    Julia only runs once, hence also includes compilation time of the function
    In the Julia example there is an additional if statement.
    Not including compile time and ii as Int and removing the if statement
    leads to a speed up of x45 on my machine.

3) The Numba version (pisum.ipy) only loops 10^5 times, not 10^6.
    The Numba version uses a different algorithm.

I don't know if I really understand the benchmark, but can you comment on the points above?

Thanks
Andre

**Comment by meresmclr** [comment]
@abieler thanks for your comments. Yes one night I furiously was editing and really didn't finish the work.
It should be much closer to sensible now, what do you think?

**Comment by abieler** [comment]
I just had a quick look at the Julia part. You are
still including the compilation time in the current version.

A few comments:

Take the x = 0.0 in f() down to the next line.

In Julia you do not need ; at the end of lines, only
when you use multiple statements in one line.
(like your if --> break statements)


Add two more lines of code:

println("simple_iter")
f(10^6)    # warm up for jit compiler
@time f(10^6)


println("pisum")
g(10^6)    # warm up for jit compiler
@time g(10^6)


The first time a function gets called in julia it is compiled (just in time
compilation),
every call after this will be using the compiled one.

There is still the inconsistency with the if-break condition that is there
in
Julia but not in the maltab simple_iter().


Generally in Julia I would recommend using the BenchmarkTools.jl package.
Pkg.add("BenchmarTools.jl")

and then simply do:

@benchmark f(10^6)
@benchmark g(10^6)


Cheers
Andre

**Comment by meresmclr** [comment]
Thanks. The latest commit addresses these issues
